In [1]:
import pandas as pd

ratings = pd.read_csv(
    "data/ratings.dat",
    sep="::",
    engine="python",
    names=["user_id", "movie_id", "rating", "timestamp"],
)

In [2]:
ratings.shape

(1000209, 4)

In [3]:
ratings.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [4]:
ratings["user_id"].nunique()

6040

In [5]:
ratings["movie_id"].nunique()

3706

In [6]:
ratings["date"] = pd.to_datetime(ratings["timestamp"],unit="s")

In [7]:
ratings.head()

   user_id  movie_id  rating  timestamp                date
0        1      1193       5  978300760 2000-12-31 22:12:40
1        1       661       3  978302109 2000-12-31 22:35:09
2        1       914       3  978301968 2000-12-31 22:32:48
3        1      3408       4  978300275 2000-12-31 22:04:35
4        1      2355       5  978824291 2001-01-06 23:38:11

In [8]:
ratings["date"].min() , ratings["date"].max()

(Timestamp('2000-04-25 23:05:32'), Timestamp('2003-02-28 17:49:50'))

In [9]:
ratings["date"].dt.to_period("M").value_counts().sort_index()

date
2000-04     11396
2000-05     67437
2000-06     54486
2000-07     90334
2000-08    182109
2000-09     52421
2000-10     42294
2000-11    290793
2000-12    113487
2001-01     18004
2001-02      8136
2001-03      6083
2001-04      5171
2001-05      4939
2001-06      4981
2001-07      4765
2001-08      4454
2001-09      3077
2001-10      2192
2001-11      2760
2001-12      3496
2002-01      3216
2002-02      2496
2002-03      2454
2002-04      2840
2002-05      1902
2002-06      1643
2002-07      1905
2002-08      2111
2002-09      1293
2002-10      1014
2002-11      1908
2002-12      1264
2003-01      1852
2003-02      1496
Freq: M, Name: count, dtype: int64

In [10]:
before_2001 = (ratings["date"] < "2001-01-01").sum()
before_2001, before_2001 / len(ratings)

(np.int64(904757), np.float64(0.9045679452994324))

In [11]:
pd.to_datetime(ratings["timestamp"].quantile(0.8), unit="s")

Timestamp('2000-12-02 14:52:18')

In [12]:
cutoff = pd.to_datetime(ratings["timestamp"].quantile(0.8), unit="s")

train = ratings[ratings["date"] < cutoff]
test = ratings[ratings["date"] >= cutoff]

In [13]:
len(train), len(test), len(train) + len(test)

(800164, 200045, 1000209)